sudo: required
services:
    - docker


before_install:
  - docker build -t oz4899/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run oz4899/react-test npm test -- --coverage

after_success:
  - docker build -t oz4899/multi-client ./client
  - docker build -t oz4899/multi-nginx ./nginx
  - docker build -t oz4899/multi-server ./server
  - docker build -t oz4899/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push oz4899/multi-client
  - docker push oz4899/multi-nginx
  - docker push oz4899/multi-server
  - docker push oz4899/multi-worker


deploy:
  provider: elasticbeanstalk
  region: ap-northeast-1
  app: multi-docker
  env: MultiDocker-env
  bucket: elasticbeanstalk-ap-northeast-1-481678475449
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

